import { Fragment } from "react"
import Head from "next/head"
import Image from "next/image"

import asset_logo from "@/assets/logo.svg"

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>yearn.today</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="px-4 max-w-screen-xl mx-auto">
        <nav className="h-24 flex items-center justify-between">
          <Image height={32} src={asset_logo} alt="yearn.today logo" />
          <button className="bg-yearn-blue py-2 text-lg px-6 rounded-full text-white">
            Connect
          </button>
        </nav>
      </main>
    </Fragment>
  )
}
